version: 2
# Dependabot configuration following recommended best practices for a mono-repo (backend + frontend)
# Docs: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

updates:
  # 1. Backend (Node / npm)
  - package-ecosystem: "npm"
    directory: "/backend"           # Location of package.json
    schedule:
      interval: "daily"             # Daily keeps PR batch manageable; adjust to "weekly" if noisy
      time: "03:00"                 # Local early morning (America/Sao_Paulo)
      timezone: "America/Sao_Paulo"
    allow:
      - dependency-type: "direct"    # Limit noise: update direct deps (lockfile updates still bring transitives)
    open-pull-requests-limit: 10
    versioning-strategy: increase
    rebase-strategy: auto
    labels:
      - "dependencies"
      - "backend"
      - "security"
    commit-message:
      prefix: "deps:backend"
      include: "scope"
  # reviewers: ["username1"]  # Uncomment and set if you want mandatory reviewers (Enterprise feature limitations may apply)
  # assignees: ["username1"]  # Optional default assignees
    groups:              # Group related updates to reduce PR noise
      jest-testing:
        patterns:
          - "jest"
          - "@types/jest"
          - "mongodb-memory-server*"
          - "supertest"
      eslint-linting:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
          - "eslint-plugin-*"
      express-stack:
        patterns:
          - "express"
          - "cors"
          - "express-rate-limit"
      mongoose-orm:
        patterns:
          - "mongoose"

  # 2. Frontend (Node / npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "03:10"                  # Stagger vs backend
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    rebase-strategy: auto
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "deps:frontend"
      include: "scope"
    groups:
      react-core:
        patterns:
          - "react"
          - "react-dom"
          - "react-scripts"
      testing-library:
        patterns:
          - "@testing-library/*"
      types-packages:
        patterns:
          - "@types/*"
      eslint-linting:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
          - "eslint-plugin-*"
      typescript-tooling:
        patterns:
          - "typescript"
      axios-lib:
        patterns:
          - "axios"

  # 3. GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"                    # Root .github/workflows
    schedule:
      interval: "weekly"              # Weekly is usually enough for actions
      day: "monday"
      time: "03:20"
      timezone: "America/Sao_Paulo"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "deps:actions"
      include: "scope"
    open-pull-requests-limit: 5

  # 4. (Comentado) Blocos específicos somente para updates de segurança foram removidos porque a validação local indicou chave 'security-updates-only' não suportada.
  #    O GitHub ainda abrirá PRs de segurança via Dependabot Alerts automaticamente.
  #    Caso seja liberado/suportado no plano atual, você pode reintroduzir blocos assim:
  #  - package-ecosystem: "npm"
  #    directory: "/backend"
  #    schedule:
  #      interval: "daily"
  #    security-updates-only: true
  #    labels: ["dependencies", "security", "backend"]

# Notes / Rationale:
# - Grouping reduces PR fatigue (especially for jest / lint / react ecosystems).
# - Prefixes in commit messages help triage and enable optional automations.
# - versioning-strategy: increase => allows minor/patch jumps; majors still raise PRs, not forced.
# - You can enable auto-merge (implemented separately) reacting to labels or conditions.
# - Adjust times to your timezone if desired.
# - Para habilitar auto-merge em uma PR específica do Dependabot: adicione o label `automerge` após os checks passarem.

# Optional: create a separate workflow to automerge safe updates (minor/patch) when CI passes & label applied.
# Example (not created automatically here):
# name: Auto-merge Dependabot
# on: pull_request
# permissions:
#   contents: write
#   pull-requests: write
# jobs:
#   automerge:
#     if: >-
#       github.actor == 'dependabot[bot]' &&
#       contains(join(fromJson(toJson(github.event.pull_request.labels)).*.name, ','), 'automerge')
#     runs-on: ubuntu-latest
#     steps:
#       - name: Enable auto-merge
#         run: gh pr merge "$PR_URL" --rebase --auto
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PR_URL: ${{ github.event.pull_request.html_url }}
