name: Static Checks

on:
  # Mantém execução manual e acrescenta gatilhos de validação direta em PRs principais
  workflow_dispatch:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]

permissions:
  contents: read

env:
  NODE_VERSION: 20.x

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          # Only reference dependency lockfiles that actually exist.
          # Using non-existent paths causes: "Some specified paths were not resolved" and breaks caching.
          cache-dependency-path: package-lock.json
      - name: Install root + workspaces (peer-safe)
        run: |
          set -e
          if [ -f package-lock.json ]; then npm ci || echo "npm ci failed"; fi
          if [ ! -d node_modules ]; then npm install --legacy-peer-deps; fi
          npm install --workspaces --legacy-peer-deps
          echo "Node $(node -v) - npm $(npm -v)"
      - name: Unified ESLint
        run: npx eslint backend frontend || (echo "Retrying after possible missing modules" && npm install --workspaces --legacy-peer-deps && npx eslint backend frontend)

  typecheck:
    name: Type Check (Frontend)
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          # Frontend has no standalone package-lock.json (monorepo root lockfile only)
          cache-dependency-path: package-lock.json
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci || npm install
      - name: TypeScript Check
        working-directory: frontend
        run: npx tsc --noEmit

# Próximos workflows (Tests and Coverage, CodeQL) vão disparar via workflow_run após sucesso deste.